
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author sams
 */
public class listBox extends javax.swing.JFrame {

    /**
     * Creates new form listBox
     */
    public listBox() {
        try {
            initComponents();
            isletmeListDoldur();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(listBox.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    DefaultListModel listModel2 = new DefaultListModel();

    public void isletmeListDoldur() throws ClassNotFoundException {
        try {

            String sql = "select * from isletmeler_yeni";
            MysqlConnect cnn = new MysqlConnect();
            Statement statement = cnn.conn().createStatement();
            ResultSet rs = statement.executeQuery(sql);//Verit

            listModel2 = new DefaultListModel();

            while (rs.next()) {
                listModel2.addElement(rs.getString(2));

            }

            jList2.setModel(listModel2);
            cnn.conn().close();
        } catch (Exception ex) {

            ex.printStackTrace();

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList2.setName("listSirketler"); // NOI18N
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jList2);

        jList3.setName("listFisler"); // NOI18N
        jList3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList3MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jList3);

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setText("İşletme Adı");

        jLabel2.setText("Seçilen İşletmeye Ait Kayıtlardaki Fişler");

        jLabel3.setText("Seçilen Fişteki Ürün Listesi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(101, 101, 101))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel2)))
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 52, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void fullFisListDoldur() throws ClassNotFoundException {
        try {
            jList3.clearSelection();
            listModel3.clear();
            String sql = "select * from fisdepo where isletme='" + jList2.getSelectedValue() + "'";
            MysqlConnect cnn = new MysqlConnect();
            Statement statement = cnn.conn().createStatement();
            ResultSet rs = statement.executeQuery(sql);//Verit
            listModel3 = new DefaultListModel();

            while (rs.next()) {
                listModel3.addElement(rs.getString(1));

            }
            jList3.setModel(listModel3);
            cnn.conn().close();
        } catch (Exception ex) {

            ex.printStackTrace();

        }

    }

    DefaultListModel listModel3 = new DefaultListModel();
    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        try {
            fisDetayListDoldur();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(listBox.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jList2MouseClicked
    public void fisDetayListDoldur() throws ClassNotFoundException {
        try {
            jList1.clearSelection();
            String sql = "select * from fisdepo where isletme='" + jList2.getSelectedValue() + "' order by fisNo";
            MysqlConnect cnn = new MysqlConnect();
            Statement statement = cnn.conn().createStatement();
            ResultSet rs = statement.executeQuery(sql);//Verit
            DefaultListModel listModel = new DefaultListModel();

            while (rs.next()) {

                listModel.addElement("İsletme adı:" + rs.getString(2));
                listModel.addElement("Fiş no:" + rs.getString(1));
                listModel.addElement("KDV:" + rs.getString(3));
                //  listModel.addElement("Urun:"+rs.getString(4));
                listModel.addElement("toplam :" + rs.getString(5));
                listModel.addElement("tarih:" + rs.getString(4));
                listModel.addElement("***************************************");
            }
            jList1.setModel(listModel);
            cnn.conn().close();
        } catch (Exception ex) {

            ex.printStackTrace();

        }

    }

    public void urunListDoldur() throws ClassNotFoundException {
        try {
            //jList1.clearSelection();
            String dizi[] = jList1.getSelectedValue().toString().split(":");
            String sql = "select * from urunler_yeni where fisNo='" + dizi[1] + "'";
            MysqlConnect cnn = new MysqlConnect();
            Statement statement = cnn.conn().createStatement();
            ResultSet rs = statement.executeQuery(sql);//VeritjList3
            DefaultListModel listModel = new DefaultListModel();

            while (rs.next()) {
                listModel.addElement("Fiş No:" + rs.getString(1));
                listModel.addElement("urunBilgileri:" + rs.getString(2));

            }
            jList3.setModel(listModel);
            cnn.conn().close();
        } catch (Exception ex) {

            ex.printStackTrace();

        }

    }

    private void jList3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList3MouseClicked


    }//GEN-LAST:event_jList3MouseClicked

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        try {
            urunListDoldur();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(listBox.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jList1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JList jList3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
